# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-26 11:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('interactive', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='dislikers',
            field=models.ManyToManyField(blank=True, related_name='dislikers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='likers',
            field=models.ManyToManyField(blank=True, related_name='likers', to=settings.AUTH_USER_MODEL),
        ),
    ]
