# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-11 11:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalChat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('about', models.CharField(max_length=200)),
                ('is_hidden', models.BooleanField()),
                ('is_public', models.BooleanField()),
                ('category', models.CharField(max_length=200)),
                ('number_of_members', models.IntegerField(default=1)),
                ('active_members', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='GlobalChatMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateTimeField()),
                ('member_status', models.CharField(max_length=200)),
                ('user_is_participant', models.BooleanField(default=True)),
                ('global_chat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chats.GlobalChat')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GlobalChatRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(max_length=200)),
                ('rating', models.FloatField(default=0.0)),
                ('global_chat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chats.GlobalChat')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_text', models.CharField(max_length=200)),
                ('created_on', models.DateTimeField()),
                ('likes', models.IntegerField(default=0)),
                ('dislikes', models.IntegerField(default=0)),
                ('global_chat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chats.GlobalChat')),
            ],
        ),
        migrations.CreateModel(
            name='SubChat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=200)),
                ('about', models.CharField(max_length=200)),
                ('is_hidden', models.BooleanField()),
                ('is_public', models.BooleanField()),
                ('number_of_members', models.IntegerField(default=1)),
                ('number_of_active_members', models.IntegerField(default=0)),
                ('global_chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chats.GlobalChat')),
            ],
        ),
        migrations.CreateModel(
            name='SubChatMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateTimeField()),
                ('member_status', models.CharField(max_length=200)),
                ('user_is_participant', models.BooleanField(default=True)),
                ('sub_chat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chats.SubChat')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubChatRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(max_length=200)),
                ('rating', models.FloatField(default=0.0)),
                ('permanent_chat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chats.SubChat')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=200)),
                ('is_hidden', models.BooleanField()),
                ('is_private', models.BooleanField()),
                ('number_of_active_participants', models.IntegerField(default=0)),
                ('global_chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chats.GlobalChat')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(upload_to='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(max_length=200)),
                ('rating', models.FloatField(default=0.0)),
                ('global_chat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chats.GlobalChat')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='sub_chat_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chats.SubChat'),
        ),
        migrations.AddField(
            model_name='message',
            name='topic_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chats.Topic'),
        ),
        migrations.AddField(
            model_name='message',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
