# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-11 11:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='globalchatmembership',
            old_name='global_chat_id',
            new_name='global_chat',
        ),
        migrations.RenameField(
            model_name='globalchatmembership',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='globalchatrating',
            old_name='global_chat_id',
            new_name='global_chat',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='global_chat_id',
            new_name='global_chat',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='sub_chat_id',
            new_name='sub_chat',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='topic_id',
            new_name='topic',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='subchatmembership',
            old_name='sub_chat_id',
            new_name='sub_chat',
        ),
        migrations.RenameField(
            model_name='subchatmembership',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='userrating',
            old_name='global_chat_id',
            new_name='global_chat',
        ),
        migrations.RenameField(
            model_name='userrating',
            old_name='user_id',
            new_name='user',
        ),
    ]
