# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-19 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatgroup',
            name='label',
            field=models.SlugField(default='slug', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='localchat',
            name='label',
            field=models.SlugField(default='slug', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topic',
            name='label',
            field=models.SlugField(default='slug', unique=True),
            preserve_default=False,
        ),
    ]
