# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-01 16:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chats', '0002_auto_20170411_1139'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatGroupMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateTimeField()),
                ('member_status', models.CharField(max_length=200)),
                ('user_is_participant', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='LocalChat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=200)),
                ('about', models.CharField(max_length=200)),
                ('is_hidden', models.BooleanField()),
                ('is_public', models.BooleanField()),
                ('number_of_members', models.IntegerField(default=1)),
                ('number_of_active_members', models.IntegerField(default=0)),
            ],
        ),
        migrations.RenameModel(
            old_name='GlobalChat',
            new_name='ChatGroup',
        ),
        migrations.RenameModel(
            old_name='GlobalChatRating',
            new_name='ChatGroupRating',
        ),
        migrations.RenameModel(
            old_name='SubChatMembership',
            new_name='LocalChatMembership',
        ),
        migrations.RenameModel(
            old_name='SubChatRating',
            new_name='LocalChatRating',
        ),
        migrations.RemoveField(
            model_name='globalchatmembership',
            name='global_chat',
        ),
        migrations.RemoveField(
            model_name='globalchatmembership',
            name='user',
        ),
        migrations.RemoveField(
            model_name='subchat',
            name='global_chat',
        ),
        migrations.RenameField(
            model_name='chatgrouprating',
            old_name='global_chat',
            new_name='chat_group',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='global_chat',
            new_name='chat_group',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='global_chat',
            new_name='chat_group',
        ),
        migrations.RenameField(
            model_name='userrating',
            old_name='global_chat',
            new_name='chat_group',
        ),
        migrations.AlterField(
            model_name='localchatmembership',
            name='sub_chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chats.LocalChat'),
        ),
        migrations.AlterField(
            model_name='localchatrating',
            name='permanent_chat_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chats.LocalChat'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sub_chat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chats.LocalChat'),
        ),
        migrations.DeleteModel(
            name='GlobalChatMembership',
        ),
        migrations.DeleteModel(
            name='SubChat',
        ),
        migrations.AddField(
            model_name='localchat',
            name='chat_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chats.ChatGroup'),
        ),
        migrations.AddField(
            model_name='chatgroupmembership',
            name='chat_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chats.ChatGroup'),
        ),
        migrations.AddField(
            model_name='chatgroupmembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
