# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-03 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0005_auto_20170803_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatgroup',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='group_avatar'),
        ),
    ]
