# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-05 14:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0006_chatgroup_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatgroupmembership',
            name='date_joined',
        ),
        migrations.AddField(
            model_name='chatgroupmembership',
            name='date_established',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
