# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-09 17:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chats', '0011_auto_20170809_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatgroup',
            name='number_of_members',
        ),
        migrations.AddField(
            model_name='chatgroup',
            name='members',
            field=models.ManyToManyField(related_name='is_member', to=settings.AUTH_USER_MODEL),
        ),
    ]
