# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-10 10:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chats', '0012_auto_20170809_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatgroupmembership',
            name='chat_group',
        ),
        migrations.RemoveField(
            model_name='chatgroupmembership',
            name='user',
        ),
        migrations.RemoveField(
            model_name='localchatmembership',
            name='local_chat',
        ),
        migrations.RemoveField(
            model_name='localchatmembership',
            name='user',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='number_of_active_participants',
            new_name='arrow_downs',
        ),
        migrations.AddField(
            model_name='topic',
            name='arrow_ups',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='topic',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='topic_avatar'),
        ),
        migrations.AddField(
            model_name='topic',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='topic',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='topic',
            name='name',
            field=models.CharField(default='Default Topic', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topic',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topic',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ChatGroupMembership',
        ),
        migrations.DeleteModel(
            name='LocalChatMembership',
        ),
    ]
