# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-10 10:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0013_auto_20170810_1046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='chat_group',
            new_name='chatgroup',
        ),
    ]
