# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-10 14:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chats', '0014_auto_20170810_1052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='localchat',
            old_name='chat_group',
            new_name='chatgroup',
        ),
        migrations.RemoveField(
            model_name='localchat',
            name='number_of_active_members',
        ),
        migrations.RemoveField(
            model_name='localchat',
            name='number_of_favs',
        ),
        migrations.AddField(
            model_name='localchat',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='local_chat_avatar'),
        ),
        migrations.AddField(
            model_name='localchat',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='localchat',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='localchat',
            name='name',
            field=models.CharField(default='Default Local Chat', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='localchat',
            name='participants',
            field=models.ManyToManyField(related_name='is_participant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='localchat',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
