# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-11 14:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0020_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='chatgroup',
        ),
        migrations.RemoveField(
            model_name='message',
            name='globalchat',
        ),
        migrations.RemoveField(
            model_name='message',
            name='localchat',
        ),
        migrations.RemoveField(
            model_name='message',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
